### PR TITLE
Add LCh structure for CIELCh colour space

### PR DESCRIPTION
**Pull request by mina86**
CIELCh is based on CIELab but uses cylindrical coordinates to represet
chromaticity.  It’s a close companion of CIELab by converting a* and b*
to polar coordinates C* and h°.

### CODE REVIEW

**Comment by TooManyBees** [comment]
Hi, thanks for your PR. Forgive me, it's going to take me a little bit to look this over, but I promise to address it next week.

**Comment by mina86** [comment]
I admit I’m being a bit lazy. I’ve added three more commits in front which update the D65 and take advantage of FMA (if available) improving accuracy overall. I can create a separate PR if you’d prefer.

**Comment by TooManyBees** [comment]
So I'm getting a couple of test errors in `test_lch_from_rgb` and `test_lch_from_lab`, both are the same assertion fail:

```diff
 [
     LCh {
         l: 66.637695,
         c: 54.321777,
<        h: 0.2770602,
>        h: 0.27706024,
 ...
```

I'm getting this on both computers that I have access to, whether using the SIMD code paths or not, and it's the same assertion error that's failing the appveyor build. Changing the `h` constant, predictably, passes tests on my machines and Appveyor, but fails Travis. Unless you have any ideas where the discrepancy is coming from, I wonder if it's time to bring in the "approx" crate, which I've so far only been using for testing the avx2 code.

**Comment by mina86** [comment]
This looks to be difference in `atan2` instruction. As far as I understand IEEE is less strict about precision of trigonometric functions than it is about other operations so there’s greater chance for discrepancies between machines.

I imagine that 
```
    #[test]
    fn test_atan2() {
        let a: f32 = 52.250145;
        let b: f32 = 14.858591;
        assert_eq!(0.2770602, b.atan2(a));
    }
```
fails for you as well?

My first guess was that it’s Intel v AMD but the tests pass for me on Ryzen 9 5900X as well as i7 7600U.

Using approximate comparisons may indeed be the only way to resolve this.

**Comment by TooManyBees** [comment]
released in 0.9.0

**Pull request merged**
